/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones = 'Europe/Paris';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    medias: Media;
    professionnels: Professionnel;
    lieux: Lieux;
    actualites: Actualite;
    activites: Activite;
    innovations: Innovation;
    partenaires: Partenaire;
    pages: Page;
    informations: Information;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    medias: MediasSelect<false> | MediasSelect<true>;
    professionnels: ProfessionnelsSelect<false> | ProfessionnelsSelect<true>;
    lieux: LieuxSelect<false> | LieuxSelect<true>;
    actualites: ActualitesSelect<false> | ActualitesSelect<true>;
    activites: ActivitesSelect<false> | ActivitesSelect<true>;
    innovations: InnovationsSelect<false> | InnovationsSelect<true>;
    partenaires: PartenairesSelect<false> | PartenairesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    informations: InformationsSelect<false> | InformationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  nom: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Images publiques destinées au site seulement. Les fichiers restent privés dans ce serveur et seuls ceux utilisés dans un contenu publié sont exportés. Une image est immuable : créer un nouveau fichier, le choisir dans un brouillon puis publier.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medias".
 */
export interface Media {
  id: number;
  alt: string;
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {};
}
/**
 * Contenu public uniquement. Ne jamais saisir de donnée patient. Publier déclenche la prochaine génération locale du site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "professionnels".
 */
export interface Professionnel {
  id: number;
  prenom: string;
  nom: string;
  titreAffiche: string;
  profession:
    'medecin-generaliste' | 'infirmier' | 'kinesitherapeute' | 'pharmacien' | 'coordination' | 'autre' | 'a-confirmer';
  professionLabel: string;
  lieux?: (number | Lieux)[] | null;
  horairesParLieu?:
    | {
        lieu: number | Lieux;
        horaires: string;
        id?: string | null;
      }[]
    | null;
  domaines?:
    | {
        libelle: string;
        id?: string | null;
      }[]
    | null;
  activites?:
    | {
        libelle: string;
        id?: string | null;
      }[]
    | null;
  telephone?: string | null;
  email?: string | null;
  doctolibUrl?: string | null;
  photo?: (number | null) | Media;
  accepteNouveauxPatients?: boolean | null;
  soinsADomicile?: boolean | null;
  slug: string;
  visible?: boolean | null;
  archive?: boolean | null;
  ordre?: number | null;
  debutAffichage?: string | null;
  finAffichage?: string | null;
  corps?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Contenu public uniquement. Ne jamais saisir de donnée patient. Publier déclenche la prochaine génération locale du site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lieux".
 */
export interface Lieux {
  id: number;
  nom: string;
  adresse: string;
  codePostal: string;
  ville: string;
  secteur?: string | null;
  telephone?: string | null;
  email?: string | null;
  horaires?: string | null;
  infosPratiques?: string | null;
  accesTransport?: string | null;
  accesPMR?: boolean | null;
  accessibilite?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  /**
   * Obligatoire avant publication. Toute modification de l’adresse ou de la position impose une nouvelle confirmation.
   */
  coordonneesVerifiees?: boolean | null;
  itineraireUrl?: string | null;
  photo?: (number | null) | Media;
  photos?:
    | {
        image?: (number | null) | Media;
        legende?: string | null;
        id?: string | null;
      }[]
    | null;
  slug: string;
  visible?: boolean | null;
  archive?: boolean | null;
  ordre?: number | null;
  debutAffichage?: string | null;
  finAffichage?: string | null;
  corps?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Contenu public uniquement. Ne jamais saisir de donnée patient. Publier déclenche la prochaine génération locale du site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "actualites".
 */
export interface Actualite {
  id: number;
  titre: string;
  date: string;
  resume: string;
  categorie: 'Actualité' | 'Prévention' | 'Santé publique' | 'Recherche' | 'Événement' | 'Vie de la MSP';
  image?: (number | null) | Media;
  epingle?: boolean | null;
  debutEvenement?: string | null;
  finEvenement?: string | null;
  slug: string;
  visible?: boolean | null;
  archive?: boolean | null;
  ordre?: number | null;
  debutAffichage?: string | null;
  finAffichage?: string | null;
  corps?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Contenu public uniquement. Ne jamais saisir de donnée patient. Publier déclenche la prochaine génération locale du site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activites".
 */
export interface Activite {
  id: number;
  titre: string;
  resume?: string | null;
  image?: (number | null) | Media;
  liens?:
    | {
        libelle: string;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  slug: string;
  visible?: boolean | null;
  archive?: boolean | null;
  ordre?: number | null;
  debutAffichage?: string | null;
  finAffichage?: string | null;
  corps?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Contenu public uniquement. Ne jamais saisir de donnée patient. Publier déclenche la prochaine génération locale du site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "innovations".
 */
export interface Innovation {
  id: number;
  titre: string;
  resume?: string | null;
  image?: (number | null) | Media;
  liens?:
    | {
        libelle: string;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  slug: string;
  visible?: boolean | null;
  archive?: boolean | null;
  ordre?: number | null;
  debutAffichage?: string | null;
  finAffichage?: string | null;
  corps?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Contenu public uniquement. Ne jamais saisir de donnée patient. Publier déclenche la prochaine génération locale du site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partenaires".
 */
export interface Partenaire {
  id: number;
  nom: string;
  description?: string | null;
  url?: string | null;
  logo?: (number | null) | Media;
  slug: string;
  visible?: boolean | null;
  archive?: boolean | null;
  ordre?: number | null;
  debutAffichage?: string | null;
  finAffichage?: string | null;
  corps?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Contenu public uniquement. Ne jamais saisir de donnée patient. Publier déclenche la prochaine génération locale du site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  titre: string;
  resume?: string | null;
  image?: (number | null) | Media;
  validationLegale?: boolean | null;
  /**
   * Choisir à la création. L’identité d’une rubrique existante est fixe ; son titre et son contenu restent modifiables.
   */
  slug:
    | 'accueil'
    | 'projet-de-sante'
    | 'soins-et-parcours'
    | 'recherche-innovation'
    | 'rejoindre'
    | 'informations-pratiques'
    | 'contact'
    | 'equipe'
    | 'lieux'
    | 'prendre-rendez-vous'
    | 'mentions-legales'
    | 'confidentialite'
    | 'accessibilite';
  visible?: boolean | null;
  archive?: boolean | null;
  ordre?: number | null;
  debutAffichage?: string | null;
  finAffichage?: string | null;
  corps?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Contenu public uniquement. Ne jamais saisir de donnée patient. Publier déclenche la prochaine génération locale du site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "informations".
 */
export interface Information {
  id: number;
  nom: string;
  nomCourt?: string | null;
  baseline?: string | null;
  description?: string | null;
  ville?: string | null;
  secteurs?:
    | {
        libelle: string;
        id?: string | null;
      }[]
    | null;
  telephone?: string | null;
  email?: string | null;
  adresse?: string | null;
  horaires?: string | null;
  contact?: {
    general?: string | null;
    secretariat?: string | null;
    coordination?: string | null;
  };
  contactsVerifies?: boolean | null;
  doctolibUrl?: string | null;
  liens?:
    | {
        libelle: string;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  slug: 'general';
  visible?: boolean | null;
  archive?: boolean | null;
  ordre?: number | null;
  debutAffichage?: string | null;
  finAffichage?: string | null;
  corps?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'medias';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'professionnels';
        value: number | Professionnel;
      } | null)
    | ({
        relationTo: 'lieux';
        value: number | Lieux;
      } | null)
    | ({
        relationTo: 'actualites';
        value: number | Actualite;
      } | null)
    | ({
        relationTo: 'activites';
        value: number | Activite;
      } | null)
    | ({
        relationTo: 'innovations';
        value: number | Innovation;
      } | null)
    | ({
        relationTo: 'partenaires';
        value: number | Partenaire;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'informations';
        value: number | Information;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  nom?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medias_select".
 */
export interface MediasSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?: T | {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "professionnels_select".
 */
export interface ProfessionnelsSelect<T extends boolean = true> {
  prenom?: T;
  nom?: T;
  titreAffiche?: T;
  profession?: T;
  professionLabel?: T;
  lieux?: T;
  horairesParLieu?:
    | T
    | {
        lieu?: T;
        horaires?: T;
        id?: T;
      };
  domaines?:
    | T
    | {
        libelle?: T;
        id?: T;
      };
  activites?:
    | T
    | {
        libelle?: T;
        id?: T;
      };
  telephone?: T;
  email?: T;
  doctolibUrl?: T;
  photo?: T;
  accepteNouveauxPatients?: T;
  soinsADomicile?: T;
  slug?: T;
  visible?: T;
  archive?: T;
  ordre?: T;
  debutAffichage?: T;
  finAffichage?: T;
  corps?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lieux_select".
 */
export interface LieuxSelect<T extends boolean = true> {
  nom?: T;
  adresse?: T;
  codePostal?: T;
  ville?: T;
  secteur?: T;
  telephone?: T;
  email?: T;
  horaires?: T;
  infosPratiques?: T;
  accesTransport?: T;
  accesPMR?: T;
  accessibilite?: T;
  latitude?: T;
  longitude?: T;
  coordonneesVerifiees?: T;
  itineraireUrl?: T;
  photo?: T;
  photos?:
    | T
    | {
        image?: T;
        legende?: T;
        id?: T;
      };
  slug?: T;
  visible?: T;
  archive?: T;
  ordre?: T;
  debutAffichage?: T;
  finAffichage?: T;
  corps?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "actualites_select".
 */
export interface ActualitesSelect<T extends boolean = true> {
  titre?: T;
  date?: T;
  resume?: T;
  categorie?: T;
  image?: T;
  epingle?: T;
  debutEvenement?: T;
  finEvenement?: T;
  slug?: T;
  visible?: T;
  archive?: T;
  ordre?: T;
  debutAffichage?: T;
  finAffichage?: T;
  corps?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activites_select".
 */
export interface ActivitesSelect<T extends boolean = true> {
  titre?: T;
  resume?: T;
  image?: T;
  liens?:
    | T
    | {
        libelle?: T;
        url?: T;
        id?: T;
      };
  slug?: T;
  visible?: T;
  archive?: T;
  ordre?: T;
  debutAffichage?: T;
  finAffichage?: T;
  corps?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "innovations_select".
 */
export interface InnovationsSelect<T extends boolean = true> {
  titre?: T;
  resume?: T;
  image?: T;
  liens?:
    | T
    | {
        libelle?: T;
        url?: T;
        id?: T;
      };
  slug?: T;
  visible?: T;
  archive?: T;
  ordre?: T;
  debutAffichage?: T;
  finAffichage?: T;
  corps?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partenaires_select".
 */
export interface PartenairesSelect<T extends boolean = true> {
  nom?: T;
  description?: T;
  url?: T;
  logo?: T;
  slug?: T;
  visible?: T;
  archive?: T;
  ordre?: T;
  debutAffichage?: T;
  finAffichage?: T;
  corps?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  titre?: T;
  resume?: T;
  image?: T;
  validationLegale?: T;
  slug?: T;
  visible?: T;
  archive?: T;
  ordre?: T;
  debutAffichage?: T;
  finAffichage?: T;
  corps?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "informations_select".
 */
export interface InformationsSelect<T extends boolean = true> {
  nom?: T;
  nomCourt?: T;
  baseline?: T;
  description?: T;
  ville?: T;
  secteurs?:
    | T
    | {
        libelle?: T;
        id?: T;
      };
  telephone?: T;
  email?: T;
  adresse?: T;
  horaires?: T;
  contact?:
    | T
    | {
        general?: T;
        secretariat?: T;
        coordination?: T;
      };
  contactsVerifies?: T;
  doctolibUrl?: T;
  liens?:
    | T
    | {
        libelle?: T;
        url?: T;
        id?: T;
      };
  slug?: T;
  visible?: T;
  archive?: T;
  ordre?: T;
  debutAffichage?: T;
  finAffichage?: T;
  corps?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}